language: java
jdk: oraclejdk8

sudo: required
install: true

addons:
  sonarqube:
    organization: "docbleach"
    token:
      secure: "ejEHtwUs4Zr0DT8uMbjXl4TiCo6bIMIVm5M6nyLyu+YUNY30TQgpNcJIDqabsHlLan6SMIZEnJ3XAOc6VqkrRDowvPPeXpSAmxcDMQrlvNyzzhBc/CTImXyZqHyjNMsivIdq+j4WQNfUpVAlPGmRacm0AokOsGj5ipo5ofYu5jc3O+6Dz8D77GjE5q91XbujmyoeLb56eF5dpT3AM7UKdStX3OS1RIBffpPuPxOqCuTSoBHIhjtpkmbNkoPMQqQsiC3QXcv604p+cVML3wOk2sDtzVH5EdLHqBFFPD9l36QBicbIXqgMVsSjw0C8fWcvue3S+p3cF3V9R/2NDXMdLV8Euc5Tu/abLNNQDcmlZAe0/Py89pHTtrPzzgixPXzrmxK7r9GckGjyQTypikKWKW3frLD6meDXt5LRSXfohKNHRfZ5hKW9xzVVKAtkRuNBhT1GSdELPXuT2rnzmzTkT/jIMp9HKOyz/TA81uZQM0L6i3W91m+UC8mI3hifh3EvWS1NAnukCtb9MJqXRNBpXhSk3Cf/G3H6m+Jo7c9Vd3o1lvXCsageHyTls9eJk8H3DOdUBazrg7MiqfRPsmvbv9gEoXwzUmLmH6Dj16XJquMvP7d/z/mlEjRoQDLPo6DoYFpVivRS1rBfoP7k8frR46bKqYjWe684mNX1w2zDfZY="
  apt:
    packages:
    - libc6-i386
    - libx11-6:i386
    - libxext6:i386
    - libxrender1:i386
    - libxi6:i386
    - libxtst6:i386
    
env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "PuwXYpDtuWdaGRqqcB71VONsss5tnmfh50n5LqOjyiAcWRVQXCvSz9VpUKYBFSp14w1KvyCgbo84itwRw+6o+ujOmTf4OPvqxLKKKDV8KbqipAwNOY6+3Nu7x7r3XokLJ1Yi3pSEXzerI6auORHySC98wV+WE0cjhaxC3Oqdsd4N/CIYcXoinLUXMaG7wLGBddB0mhkrHGdyYnsY8BStdwpJAtWwZs7q6vrFI6K4H6VYJlYxtF1CiocYWRh2ZSteK4W7I60938BP+39Oiz3b0FMHLIHZr2vr3Xgx2JpH77MIDhEWm7fMHDDJbC+PljFT0X8/50BJlHDs5sKpq5TUC0CMSrbn5kaopbDmaCW8AyuCyIFQQpA6hZyxKXxly3gHjUqL1GAtFGk/1zgq/PdXub7T808BsZ45LvWiLcVNub6x51p6LenTxMUiEgcWuismdOwnBdSGCCXx1CIJ9BrAmR+SXC0z+vxWMTXk0mgkmnS+bggkNCqDYL2PNk2OlEQjlS9Nsfo5fIk0bPY0pQnBPl08MllOA3h3zaB49Waro1EM2za4PzWDYt8LrqEYyX/ZyH/HuAm9ZtvhakYnlpSf50+w2MgYG15XIioQwLbRee3OotxUfvKclRSIPNs8PkFA5PfIm+kLR4T6oDwzBijdbwA0exlhK5T5xnidKb4l9f4="

cache:
  directories:
  - '$HOME/.m2'
  - '$HOME/.sonar/cache'

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package
  - ./scripts/jet-build.sh

deploy:
  - provider: script
    script: scripts/publish.sh
    on:
      branch: master
      repo: docbleach/DocBleach
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "qlyOP0Lg06ThcbsEgXW3qaZzS7eMmsZ4XRUVDsYXbnbZFDem46I7fPboZcAAp0g6AX79Kf/NpESfNShGgzoUZlbFkPp5ez/emi48jENv1H7HwDGS6b/rEcUo7V0ktrY3SfCeQhlwOqicMkCqDG8HT1zjK6odlvjSmSFgUcNG2fWsSmQUJkPZW2jzJaO3Ko37sgX/GIo/HgjL7N9Y7P/+/9PPdBV+rGcjLJAgLZgEQVS3OCd2XHPn6AWa0J7ieFn7JzYQXNT6iOfMVnrRsjsMuTLQKbclFgJb8SZfzJdrOaLY259JumSmGe5Y7SsuN2bRRmFt3H6yF46qptjlPz7ozJCuE4DozVowCjoY+U5ecvx6oMg5WFsFbAipaMWIe6LlZCajqN6RGgPeYwZlfIBbHmj3KGwXOrd3HCslL+D4ZDv/+9QfRriESgaJSSwI/IkT2thHDY+D7FTyRCmKY6S3jcxNGaFz4WRJeFTKMMq1vI0+wI41mRbOg7n5kaNdbCO4vXpBNC/Zhnv0DOD8Zhy/LyGnm9hlfJ10+SF6bxmdKdln9i49AdyaHzVDZCR1/X1lM6mfk1lryzj0jsYVNmYN7JhcsLiUGSY0zSrtSCMQmvajjuPPMFqWXFTj/Kz6aCCIlbsZQAHTntnQr21VMaWqa8JUJ3E6vJYZf1ZtKIy0mpk="
    file:
      - cli/target/docbleach.jar
      - cli/target/jet/docbleach.zip
    on:
      repo: docbleach/DocBleach
      tags: true
