version: '{build}'

todo: skip_non_tags: true
todo: skip_branch_with_pr: true

branches:
  only:
    - master

image: Visual Studio 2017

environment:
  JET_URL:
    secure: ATEri4q0jtlpP93k4+i1Q0dwKzP/QF7Jz8KceiPPQvaW5+7C5MfOUqd9JzQS9Ej9n/4yp0Kv0O3MfUxSD0xybX6RYHGB2H+KahM9vROyrhs2cKD6lAjT8+AuZSUeYrTC

install:
  - ps: Start-FileDownload '$JET_URL'
  - ps: .\jet-1130-std-en-windows-x86.exe -batch -no-aftrun -dest C:\jet\
  - cmd: SET JET_HOME=C:\jet\

build_script:
  - mvn clean install
  - mvn jet:build -pl cli --batch-mode -DskipTest 

cache:
  - C:\Users\appveyor\.m2
  - .\jet-1130-std-en-windows-x86.exe

artifacts:
  - path: cli/target/jet/docbleach.exe
    name: DocBleach_Setup.exe

  - path: cli/target/jet/app/
    name: DocBleach_Standalone
    type: zip

deploy:
  - provider: GitHub
    on: # release tags from branch jet-built branch only
      branch: jet-built
      appveyor_repo_tag: true
